exporter_name: products_csv
exporter_type: csv
collection: products
fields:
  - header: "gid"
    path: "_gid"
  - header: "created_at"
    path: "_created_at"
  - header: "title"
    path: "title"
  - header: "price"
    path: "price"
  - header: "feedback"
    path: "feedback"
  - header: "seller"
    path: "seller"
  - header: "test_value"
    path: "test_value"
  - header: "test_value_b"
    path: "test_value_b"
export_filename: my_csv_SID:<sid>_NAME:<name>_JID:<jid>_DATE:<d:yyyyMMdd hh:mm>
